;;(require 'w3m)
(require 'color-theme)
(color-theme-initialize)

(defun ime-corsor-colors ()
"set ime on/off colors"
(add-hook 'mw32-ime-on-hook
(function (lambda ()
(set-cursor-color "orange1"))))
(add-hook 'mw32-ime-off-hook
(function (lambda ()
(set-cursor-color "white")))))

(defun my-hilit-chg-colors ()
"set hilit chg colors"
;; (set-face-foreground 'highlight-changes-face "cyan")
;; (set-face-background 'highlight-changes-face "dark cyan")
;; (set-face-foreground 'highlight-changes-delete-face "cyan")
;; (set-face-background 'highlight-changes-delete-face "dark cyan")
(setq highlight-changes-colors nil)
(set-face-foreground 'highlight-changes-face "SkyBlue1")
(set-face-background 'highlight-changes-face "DeepSkyBlue4")
(set-face-foreground 'highlight-changes-delete-face "SkyBlue1")
(set-face-background 'highlight-changes-delete-face "DeepSkyBlue4"))

(defun my-w3m-colors ()
"set w3m colors"
(set-face-foreground 'w3m-anchor-face "white")
(set-face-background 'w3m-anchor-face "#555")
(set-face-foreground 'w3m-arrived-anchor-face "white")
(set-face-background 'w3m-arrived-anchor-face "#555")
(set-face-foreground 'w3m-image-face "white"))

(defun my-dark-font-lock ()
"my dark font lock"
(interactive)
(color-theme-install
'(color-theme-dark-font-lock
nil
(font-lock-builtin-face ((t (:foreground "white"))))
;; (font-lock-builtin-face ((t (:foreground "indian red"))))
(font-lock-comment-face ((t (:foreground "#998"))))
(font-lock-constant-face ((t (:foreground "white"))))
(font-lock-doc-string-face ((t (:foreground "#998"))))
(font-lock-doc-face ((t (:foreground "#998"))))
(font-lock-function-name-face ((t (:underline t :background "#555" :foreground "white"))))
(font-lock-keyword-face ((t (:foreground "white"))))
;; (font-lock-keyword-face ((t (:foreground "indian red"))))
(font-lock-preprocessor-face ((t (:foreground "white"))))
(font-lock-reference-face ((t (:foreground "white"))))
(font-lock-string-face ((t (:background "#210" :foreground "#987"))))
;; (font-lock-string-face ((t (:background nil :foreground "steel blue"))))
(font-lock-type-face ((t (:foreground "white"))))
(font-lock-variable-name-face ((t (:foreground "white"))))
(font-lock-warning-face ((t (:foreground "white")))))))

(defun my-late-night ()
"my late night"
(interactive)
(let ((color-theme-is-cumulative t))
(color-theme-dark-erc)
(color-theme-dark-gnus)
;; (color-theme-dark-diff)
;; (color-theme-dark-eshell)
(color-theme-dark-info)
(my-dark-font-lock)
(ime-corsor-colors)
;; (my-hilit-chg-colors)
;;(my-w3m-colors)
(color-theme-install
'(color-theme-late-night
((background-color . "black")
(background-mode . dark)
(background-toolbar-color . "black")
(border-color . "black")
(bottom-toolbar-shadow-color . "black")
(cursor-color . "white")
(foreground-color . "#ddd")
(top-toolbar-shadow-color . "#111"))
(default ((t (nil))))
(bold ((t (:bold t))))
(button ((t (:bold t))))
(custom-button-face ((t (:bold t :foreground "#999"))))
(fringe ((t (:background "#111" :foreground "#444"))))
(header-line ((t (:background "#111" :foreground "#aaa"))))
(highlight ((t (:background "dark slate blue" :foreground "light blue"))))
(holiday-face ((t (:background "#666" :foreground "#fff"))))
(isearch ((t (:foreground "cyan" :background "dark cyan"))))
(isearch-lazy-highlight-face ((t (:foreground "cyan"))))
(italic ((t (:bold t))))
(menu ((t (:background "#111" :foreground "#aaa"))))
(minibuffer-prompt ((t (:background "#000" :foreground "#aaa"))))
(modeline ((t (:background "#333" :foreground "#aaa"))))
(mode-line-inactive ((t (:background "#000" :foreground "#444"))))
(modeline-buffer-id ((t (:background "#000" :foreground "#555"))))
(modeline-mousable ((t (:background "#000" :foreground "#555"))))
(modeline-mousable-minor-mode ((t (:background "#000" :foreground "#555"))))
(region ((t (:background "dark cyan" :foreground "cyan"))))
(secondary-selection ((t (:background "Aquamarine" :foreground "SlateBlue"))))
(show-paren-match-face ((t (:foreground "white" :background "light slate blue"))))
(show-paren-mismatch-face ((t (:foreground "white" :background "red"))))
(tool-bar ((t (:background "#333" :foreground "#fff"))))
(tooltip ((t (:background "#333" :foreground "#fff"))))
(underline ((t (:bold t))))
(variable-pitch ((t (nil))))
(widget-button-face ((t (:bold t :foreground "#888"))))
(widget-field-face ((t (:bold t :foreground "#999"))))))))